In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
st = pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\INT-234-CA-2 Project\Classification\satellite_dataset_18_columns.csv")
st.head()

,timestamp,temperature_c,humidity_percent,pressure_pa,gas_ppm,radiation_uSv_h,battery_voltage_v,solar_current_ma,cpu_temp_c,vibration_mms,satellite_mode,region,fault_flag,battery_voltage_next,altitude_m,magnetic_field_uT,solar_panel_temp_c,gyro_stability_index
0,2025-01-01 00:00:00,21.83,31.41,100495.90,NaN,0.0870,7.631,443.92,30.52,2.527,NaN,EUROPE,NO,8.492,399833.626619,NaN,41.105207,0.211557
1,2025-01-01 00:00:01,13.76,37.19,101770.60,344.31,0.0619,6.847,312.65,50.26,2.523,ACTIVE,AFRICA,YES,7.433,400466.959447,44.358010,23.396596,0.210636
2,2025-01-01 00:00:02,24.50,18.22,101295.98,188.44,0.1733,7.328,533.32,47.60,2.344,NaN,AMERICA,NO,NaN,400204.991027,47.145225,NaN,0.414807
3,2025-01-01 00:00:03,25.64,27.72,101025.05,264.16,NaN,7.073,228.89,39.94,3.353,ACTIVE,ASIA,NO,7.518,400295.221921,47.505118,NaN,0.846881
4,NaN,8.29,NaN,101199.59,320.70,0.0000,8.259,148.30,35.75,1.690,NaN,AMERICA,NO,8.562,399774.287427,NaN,12.736427,0.274114

In [3]:
st.isnull().sum()

timestamp               827
temperature_c           817
humidity_percent        752
pressure_pa             774
gas_ppm                 785
radiation_uSv_h         790
battery_voltage_v       764
solar_current_ma        844
cpu_temp_c              815
vibration_mms           768
satellite_mode          806
region                  767
fault_flag              779
battery_voltage_next    773
altitude_m              801
magnetic_field_uT       789
solar_panel_temp_c      806
gyro_stability_index    814
dtype: int64

In [4]:
def num_null(col):
    for c in col:
        st[c] = st[c].fillna(st[c].mean())

def cat_null(col):
    for c in col:
        st[c] = st[c].fillna(st[c].mode()[0])

In [5]:
num_cols = st.select_dtypes(include="float").columns
cat_cols = st.select_dtypes(include="object").columns

num_null(num_cols)
cat_null(cat_cols)

In [6]:
st.isnull().sum()

timestamp               0
temperature_c           0
humidity_percent        0
pressure_pa             0
gas_ppm                 0
radiation_uSv_h         0
battery_voltage_v       0
solar_current_ma        0
cpu_temp_c              0
vibration_mms           0
satellite_mode          0
region                  0
fault_flag              0
battery_voltage_next    0
altitude_m              0
magnetic_field_uT       0
solar_panel_temp_c      0
gyro_stability_index    0
dtype: int64

In [7]:
lb = LabelEncoder()
def encode(col):
    for c in col:
        st[c] = lb.fit_transform(st[c])

encode(cat_cols)

In [8]:
st.head()

,timestamp,temperature_c,humidity_percent,pressure_pa,gas_ppm,radiation_uSv_h,battery_voltage_v,solar_current_ma,cpu_temp_c,vibration_mms,satellite_mode,region,fault_flag,battery_voltage_next,altitude_m,magnetic_field_uT,solar_panel_temp_c,gyro_stability_index
0,0,21.83,31.410000,100495.90,348.557987,0.087000,7.631,443.92,30.52,2.527,2,3,0,8.492000,399833.626619,45.042701,41.105207,0.211557
1,1,13.76,37.190000,101770.60,344.310000,0.061900,6.847,312.65,50.26,2.523,0,0,1,7.433000,400466.959447,44.358010,23.396596,0.210636
2,2,24.50,18.220000,101295.98,188.440000,0.173300,7.328,533.32,47.60,2.344,2,1,0,8.080327,400204.991027,47.145225,24.898949,0.414807
3,3,25.64,27.720000,101025.05,264.160000,0.148778,7.073,228.89,39.94,3.353,0,2,0,7.518000,400295.221921,47.505118,24.898949,0.846881
4,0,8.29,30.176755,101199.59,320.700000,0.000000,8.259,148.30,35.75,1.690,2,1,0,8.562000,399774.287427,45.042701,12.736427,0.274114

In [9]:
st = st.drop(columns=["timestamp"])

In [10]:
X = st.drop("fault_flag", axis=1)
y = st["fault_flag"]

scl = StandardScaler()
Xs = scl.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(Xs, y, test_size=0.2, random_state=42, stratify=y)

In [12]:
ml = SVC()
ml.fit(X_train, y_train)

yp = ml.predict(X_test)

acc = accuracy_score(yp, y_test)
cm = confusion_matrix(yp, y_test)

In [13]:
print("Accuracy: ", acc* 100,"%")
print("Confusion Matrix: \n", cm)

Accuracy:  90.9 %
Confusion Matrix:
 [[1818  182]
 [   0    0]]

In [14]:
import joblib as jb

jb.dump(ml, "SVC_SAT_NOVA.pkl")

['SVC_SAT_NOVA.pkl']